### ISSUE TITLE
[Nomination] I would like to nominate Jacob (Faddat)

### ISSUE THREAD

**Issue by blockcreators** [CosmosContracts/hack-juno#11]
**Who are you nominating?**
Jacob aka Faddat

**What are you nominating them for?**
Being an active contributor in the discord and helping update the Juno code to the latest versions.
Helping smaller validators with issues.

**Please provide links to their work.**
https://github.com/CosmosContracts/Juno/commit/c0e7cf894e90dad8c650bbc3fff9b7b2ab87168a
https://github.com/CosmosContracts/Juno/commit/2b03ba3234b4870dafe9992eb1d00f74360b3e1e
https://github.com/CosmosContracts/Juno/commit/d4cc921c5d6a60cde4dad5d6e328e4c13c41f9f4

https://github.com/CosmosContracts/Juno/commit/213ab84803113517e035c9f5f5858e65c146b199
https://github.com/CosmosContracts/Juno/commit/dd0a95b272690f9e0581ac9a736425d6462cbf2e
https://github.com/CosmosContracts/Juno/commit/854faed2c0e91592543386386b9274f4895428c2
https://github.com/CosmosContracts/Juno/commit/b509b0db7a13d16ea4e2dce0dfa12f4962c5cd8d
https://github.com/CosmosContracts/Juno/commit/53ff6aaae486f0cf09f0e7550c1e108e777c5fc5

**Comment by JakeHartnell** [comment]
Second!

**Comment by blockcreators** [comment]
He also help test taking down a juno validator on akash

**Comment by blockcreators** [comment]
Also 0.43 upgrade + dockerization

**Comment by JakeHartnell** [comment]
@faddat has been awesome! Extremely helpful in getting IBC relayers setup so we can connect to Osmosis.
