### ISSUE TITLE
[Nomination] Ben2x4

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/hack-juno#12]
**Who are you nominating?**
@ben2x4

**What are you nominating them for?**
- Creating a working AMM contract that allows for swapping CW20 tokens.
- Creating a cw20 token sale contract.
- Work on the WasmSwap Dapp.
- Creating a vesting tokens contract
- Making great contributions to cw-DAO

**Please provide links to their work.**
https://github.com/ben2x4/crustacean-swap
https://github.com/Wasmswap/wasmswap
https://github.com/Wasmswap/wasmswap-interface
https://github.com/ben2x4/cw20-sale-contract
https://github.com/ben2x4/cw-vest
https://github.com/jakehartnell/cw-dao (see Insights)

**Comment by blockcreators** [comment]
I agree! Well done Ben2x4 amazing work and look forward to the IBC transfers!

**Comment by the-frey** [comment]
Was just about to nominate Ben2x4 as well, seconded!

**Comment by Highlander-maker** [comment]
Amazing work. Glad to see some great things being put together. Great work ben. i also add to the nomination list.

**Comment by JakeHartnell** [comment]
Updated nomination to include token sale contract: https://github.com/ben2x4/cw20-sale-contract

: )

**Comment by ben2x4** [comment]
Thanks so much everyone! 🎉

**Comment by JakeHartnell** [comment]
More to add. @ben2x4 has also worked on the WasmSwap dApp, created a vesting contract, and has been actively contributing to the cw-DAO contract!
