### ISSUE TITLE
[Nomination] giansalex

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/hack-juno#13]
**Who are you nominating?**
@giansalex (Giancarlos Salas)

**What are you nominating them for?**
Being an OUTSTANDING contributor. Also for running, RPC nodes for lucina. :pray: 

**Please provide links to their work.**
- Updgrading the [CosmWasm code explorer](https://github.com/CosmWasm/code-explorer) CosmJS verision, adding Keplr support, and showing transaction time in the execution info. https://github.com/CosmWasm/code-explorer/pull/62
- Gitpod Workspace https://github.com/giansalex/cosmwasm-workspace
- Keplr CW20 tokens: Fix Add Token (cw20) chainapsis/keplr-extension#134
- cosmwasm dApps upgrade: Stargate v0.25 upgrade CosmWasm/dApps#81
- dApps works on Juno
https://dapps.juno.giansalex.dev/names/
https://dapps.juno.giansalex.dev/cw20-wallet/
https://dapps.juno.giansalex.dev/staking/
https://github.com/disperze/wrapped-dapp

- Add custom mint module juno#36
- Split contract: https://github.com/disperze/cw-contracts/tree/master/contracts/split
- Lockbox contract: https://github.com/disperze/cw-contracts/tree/master/contracts/lockbox
- Wrap contract https://github.com/disperze/cw-contracts/tree/master/contracts/wrap
- NFT-Marketplace - Cosmverse - https://github.com/CosmosContracts/Cosmverse
- Contracts - cw721, nft-market

**Comment by giansalex** [comment]
Append:
- Dark theme
- Upload wasm binary
- Instantiate new contracts

Live: https://blueprints.juno.giansalex.dev/

**Comment by blockcreators** [comment]
He also got Juno balance and add token working with keplr.

**Comment by blockcreators** [comment]
Also inflation module code

**Comment by giansalex** [comment]
Additional:
- Gitpod Workspace https://github.com/giansalex/cosmwasm-workspace
- Keplr CW20 tokens: https://github.com/chainapsis/keplr-extension/pull/134
- cosmwasm dApps upgrade: https://github.com/CosmWasm/dApps/pull/81
- dApps works on Juno
    - https://dapps.juno.giansalex.dev/names/
    - https://dapps.juno.giansalex.dev/cw20-wallet/
    - https://dapps.juno.giansalex.dev/staking/
    - https://github.com/disperze/wrapped-dapp
- Juno chain
     - https://github.com/CosmosContracts/Juno/pull/36
     - https://github.com/CosmosContracts/juno/pull/46
     - [Additional contributions](https://github.com/CosmosContracts/juno/pulls?q=is%3Apr+author%3Agiansalex)
- Split contract: https://github.com/disperze/cw-contracts/tree/master/contracts/split
- Lockbox contract: https://github.com/disperze/cw-contracts/tree/master/contracts/lockbox

- NFT-Marketplace - *Cosmverse*
   - dApp - https://github.com/CosmosContracts/Cosmverse
   - Contracts - [nft-market](https://github.com/disperze/cw-contracts/tree/cw-nft-market/contracts/nft-market)

**Comment by JakeHartnell** [comment]
A duplicate nomination for @giansalex (because he's so awesome): https://github.com/CosmosContracts/hack-juno/issues/15

**Comment by JakeHartnell** [comment]
Updated the nomination, there is so much to say. : )

**Comment by nullmames** [comment]
copied from https://github.com/CosmosContracts/hack-juno/issues/65

Who are you nominating?

Giansalex @giansalex

What are you nominating them for?

Several months of work on Cosmverse the first NFT marketplace on Juno in collaboration with Highlander

Please provide links to their work.

https://cosmverse.com

**Comment by nullmames** [comment]
closing https://github.com/CosmosContracts/hack-juno/issues/65
