### ISSUE TITLE
[Nomination] nullMames

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/hack-juno#16]
**Who are you nominating?**
@nullmames

**What are you nominating them for?**
Juno guides. Specifically the instructions for deploying Juno on Akash.

**Please provide links to their work.**
https://nullmames.gitbook.io/guides/

**Comment by JakeHartnell** [comment]
Looking forward to what you do next @nullmames. : )

**Comment by nullmames** [comment]
thanks for the nomination

**Comment by blockcreators** [comment]
Not to mention all the help he provides everyone in the discord and other coding work :)

**Comment by blockcreators** [comment]
He also got a Juno validator working on Akash

**Comment by blockcreators** [comment]
https://docs.junochain.com/command-line-interface/cli-introduction

Lots of documentation for the juno cli

**Comment by nullmames** [comment]
> 
> 
> **Who are you nominating?**
> @nullmames
> 
> **What are you nominating them for?**
> Juno guides. Specifically the instructions for deploying Juno on Akash.
> 
> **Please provide links to their work.**
> https://nullmames.gitbook.io/guides/

This guide has been moved FYI

https://docs.junochain.com/validators/deploy-a-node-on-akash

**Comment by blockcreators** [comment]
nullMames has also being helping people check if they were eligible for the stakedrop.

**Comment by JakeHartnell** [comment]
Wanted to add another contribution! @nullmames helped me with getting testnet docs ready for the upcoming hera testnet. Very much appreciated: https://github.com/CosmosContracts/testnets/pull/42

**Comment by JakeHartnell** [comment]
@nullmames was also very helpful when we were testing out the CI scripts for the `hera` testnet. He tested a bunch of different invalid gentx files: https://github.com/CosmosContracts/testnets/pull/53

**Comment by JakeHartnell** [comment]
Shout out to @nullmames for helping proof read the instructions for mainnet gentx submission as well as test the CI. He found a bug and made a PR to make the instructions more clear: https://github.com/CosmosContracts/mainnet/pull/6

**Comment by nullmames** [comment]
other docs/tutorials
https://docs.junochain.com/tutorials/wallets
https://docs.junochain.com/tutorials/wallets/keplr-browser-extension
https://docs.junochain.com/tutorials/staking
https://docs.junochain.com/tutorials/staking/omniflix-platform
https://docs.junochain.com/validators/getting-setup
https://docs.junochain.com/validators/joining-mainnet
https://docs.junochain.com/validators/joining-the-testnets
https://docs.junochain.com/validators/relayers
https://docs.junochain.com/cli/modules (12 individual modules)
https://docs.junochain.com/validators/deploy-a-node-on-akash

+ contributions to many other pages.
