### ISSUE TITLE
[Nomination] A bunch of people

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#21]
**Who are you nominating?**

I want to nominate: 
🔸 Vadim validator cyberG - https://twitter.com/vadyhodler777
🔸 Jack Zampolin - https://twitter.com/jack_zampolin
🔸 Daya from OmniFlix Network  - https://t.me/devfreakk
🔸 Sistla from OmniFlix Network -  https://twitter.com/svabhishek
🔸 Nikita from validator web34ever  - https://twitter.com/web34ever
🔸 Validator Highlander Nodes - https://twitter.com/HighlanderNodes

**What are you nominating them for?**

All of them was participating in The Validator Show #6 - Juno Network: Testing the Cosmos (second try)
They was participate 2 times in show, and two times they was telling a lot of useful and interesting information about Juno Network and validation, but I was making mistake, so the first time video wasn't record.
But this validators was finding time to participate in show 2nd time, to tell a lot of interesting about Juno Network!
They don't get nothing for participation in show, and for part of them it's not so easy to speak in English, but this is wasn't a border to them, to speak about Juno Network!
Their behavior shows that they are really interested in validation and Juno Network, and they show that they are ready to bring any kinds of value to the Network, not only security.
They always ready to help, and they actively participate in many different initiatives of the Cosmos Ecosystem projects, so they bring to Juno Network many social and cultural value, like an education, solidarity and social contacts.
I don't know how we can compare such kind of value with value from developers, but I sure, that such kind of value also very important, because they make connections between community members better, and the main for us, like a humans, and for the blockchain - is connection!

**Please provide links to their work.**

https://youtu.be/ggRdwiGduCY
https://twitter.com/synctems/status/1416543131340771329
https://t.me/JunoNetwork/15228

**Comment by Highlander-maker** [comment]
Really appreciate this. Ive spent a great deal of time working on juno and learning code. Its nice for that to be noticed.

**Comment by danvans007** [comment]
Can I 2nd this motion all the above deserve nominating.. every who has been nominated deserves it’s.. congrats and hats off to everyone. Juno for life 🔥

**Comment by nullmames** [comment]
Nominations menitioned elsewhere. closing
