### ISSUE TITLE
[Nomination] Space Potato

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/hack-juno#22]
**Who are you nominating?**
The one and only Space Potato!

**What are you nominating them for?**
They have been amazingly helpful debugging when we ran into issues on the Testnet.

**Please provide links to their work.**
There have been a couple examples of this. I remember that when we had an invalid genesis file for `lucina`, the potato was working hard to figure out which Gentxs were incorrect. Recently, he has helped with testing the CI setup for the `hera` testnet.

A recent example from the chat where Potato found a link that was wrong: https://discord.com/channels/816256689078403103/838144901585698837/883136041643560960

He was very helpful with reviewing the CI script:
https://discord.com/channels/816256689078403103/838144901585698837/883213524925558784

**Comment by JakeHartnell** [comment]
CC @spacepotahto

**Comment by JakeHartnell** [comment]
https://github.com/CosmosContracts/testnets/pull/74

**Comment by JakeHartnell** [comment]
More good stuff from our favorite spud: https://github.com/CosmWasm/cw-plus/pull/406

**Comment by spacepotahto** [comment]
In case contributing to the junochain website counts too: https://github.com/CosmosContracts/website/pull/14

**Comment by JakeHartnell** [comment]
> In case contributing to the junochain website counts too: [CosmosContracts/website#14](https://github.com/CosmosContracts/website/pull/14)

Definitely does. :pray:
