### ISSUE TITLE
[Nomination] elgorithm (ebaker)

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/hack-juno#23]
**Who are you nominating?**
Discord: elgorithm
GitHub: @ebaker

**What are you nominating them for?**
For building an awesome CosmWasm / Keplr / Next.js starter kit to make it really easy to build Juno Dapps.

**Please provide links to their work.**
https://github.com/ebaker/next-cosmwasm-keplr-starter

**Comment by JakeHartnell** [comment]
Another substantial contribution worth celebrating: https://github.com/ebaker/cw3-fixed-multisig-dapp

Really cool dapp for managing a multisig like Gnosis Safe. Amazing work @ebaker!

**Comment by natlotzy** [comment]
I used the CosmWasm / Keplr / Next.js starter kit to build a Juno dApp and it was awesome. Thanks @ebaker!

**Comment by JakeHartnell** [comment]
A payment splitter contract too: https://github.com/ebaker/cw-payment-splitter

**Comment by JakeHartnell** [comment]
Massive contribution here: https://github.com/DA0-DA0/cw-dao-dapp

This is the first DAO UI in the Juno ecosystem. : )
