### ISSUE TITLE
[Nomination] POSTHUMAN

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#28]
**Who are you nominating?**

I nominate myself: <br />
TG: https://t.me/antropocosmist <br />
GitHub: https://github.com/Antropocosmist <br />

**What are you nominating them for?**

I made a video about smart-contracts, and evolution of smart-contracts. <br />
In this video, I tell about Juno Network, as about "the highest level of evolution of smart-contracts", as Juno Network is really the top of inter-operable smart-contracts that are powered by the community.  <br />
Also, I speak about HackJuno, and tell to the people about different possibilities to participate in HackJuno. <br />
Video is in russian language, and with english subtitles. <br />
All information about Juno Network and HackJuno - in the description of video. <br />
After video a lot of new people joined russian-speaking community of Juno Network: https://t.me/juno_ru <br />

**Please provide links to their work.**

https://youtu.be/ucCIx_AsbRs

**Comment by JakeHartnell** [comment]
From #32:

> What are you nominating them for?
For the article-guide "Juno Network: How to add Juno-testnet to Keplr and get test-$JUNO", that bring a lot of new users to community, and also was really helpful in testing of Juno Network, and https://juno.omniflix.co/
It shows real usability of Juno Network, and give a practice for users.
This guide was one of the first guides about Juno, and a lot of people join community after it.
> https://antropocosmist.medium.com/juno-testnet-guide-6269baa3fc05

**Comment by JakeHartnell** [comment]
@cybernekit from #37:

> Who are you nominating?
POSTHUMAN validator: @Antropocosmist

> What are you nominating them for?
> for help in organizing and editing the video workshop "Deploying smart contracts on the Juno network" part 1 + part 2
> It will take a long time to organize an event, record a video, edit a video and upload a video, and then a promo video. Much more than just deploying a smart contract.
> And now we have 2 awesome videos to help deploy a smart contract on the Juno network!

> Part 1: https://youtu.be/xjGj8PIkrKU
> Part 2: https://youtu.be/SuPByXkjbKk

**Comment by JakeHartnell** [comment]
@Vgk88 from #38:

> **Who are you nominating?**
> 
> Validator POSTHUMAN - https://t.me/Antropocosmist
> 
> **What are you nominating them for?**
> 
> For helping in "The Validator Show #6 | Juno Network: Testing the COSMOS" and editing video
> 
> **Please provide links to their work.**
> 
> https://youtu.be/ggRdwiGduCY

**Comment by JakeHartnell** [comment]
From #29:

> **Who are you nominating?**
> 
> I nominate myself: TG: https://t.me/antropocosmist GitHub: https://github.com/Antropocosmist
> 
> **What are you nominating them for?**
> 
> I've create russian-speaking community of Juno Network in TG. I translate infrormation about Juno Network in russian, and answering on a questions about Juno Network to community members. For now (18.09.2021), russian-speaking community have 125 real members. Many of them participate in HackJuno, after they joined group, and I explain them, how they can contribute to Juno Network.
> 
> **Please provide links to their work.**
> 
> https://t.me/juno_ru

**Comment by JakeHartnell** [comment]
From #30:
> **Who are you nominating?**
> 
> I want to nominate two validators from the test-net of Juno Network: Secure Secrets and POSTHUMAN
> 
> **What are you nominating them for?**
> 
> Validator Secure Secrets create great article about HackJuno, that is helping to spread information about HackJunom and attract more people to HackJuno.
> 
> Validator POSTHUMAN was translating this article in russian language, and also adopt this translation for russian-speakers. It helps to make HackJuno more decentralized, and attract more people to participate in HackJuno.
> 
> **Please provide links to their work.**
> 
> English (now it's not available, but it was available): https://securesecrets-org.medium.com/hack-juno-create-build-earn-d91ab527c35
> 
> Russian: https://antropocosmist.medium.com/hackjuno-ru-42e53ec0cc78

**Comment by JakeHartnell** [comment]
From #53:

> Who are you nominating?

> https://github.com/Antropocosmist

> What are you nominating them for?

> For full video guide, how to add $JUNO to Kepler + how to buy $JUNO at Osmosis + how to stake (delegate_ $JUNO with OmniFlix + how to vote for proposals in Juno Network with OmniFlix + for explanation of how all it works

> Please provide links to their work.

> https://youtu.be/Z-M8pBSVks0
