### ISSUE TITLE
[Nomination] Myself for creating russian-speaking community of Juno Network

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#29]
**Who are you nominating?**

I nominate myself: <br />
TG: https://t.me/antropocosmist <br />
GitHub: https://github.com/Antropocosmist <br />

**What are you nominating them for?**

I've create russian-speaking community of Juno Network in TG. <br />
I translate infrormation about Juno Network in russian, and answering on a questions about Juno Network to community members. <br />
For now (18.09.2021), russian-speaking community have 125 real members. <br />
Many of them participate in HackJuno, after they joined group, and I explain them, how they can contribute to Juno Network. <br />

**Please provide links to their work.**

https://t.me/juno_ru

**Comment by JakeHartnell** [comment]
Moving to #28
