### ISSUE TITLE
[Nomination] Validator Secure Secrets

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#30]
**Who are you nominating?**

I want to nominate two validators from the test-net of Juno Network: Secure Secrets and POSTHUMAN <br />

**What are you nominating them for?**

Validator Secure Secrets create great article about HackJuno, that  is helping to spread information about HackJunom and attract more people to HackJuno. <br />

Validator POSTHUMAN was translating this article in russian language, and also adopt this translation for russian-speakers. It helps to make HackJuno more decentralized, and attract more people to participate in HackJuno. <br />

**Please provide links to their work.**

English (now it's not available, but it was available): <br />
https://securesecrets-org.medium.com/hack-juno-create-build-earn-d91ab527c35

Russian: <br />
https://antropocosmist.medium.com/hackjuno-ru-42e53ec0cc78

**Comment by JakeHartnell** [comment]
Making this page about Secure Secrets validator. Feel free to add other info about Secure Secrets work here.

I'll start! Secure Secrets extremely helpful during the early testnets, and I really appreciated it.

**Comment by JakeHartnell** [comment]
Will also mention this on #28. : )
