### ISSUE TITLE
[Nomination] Nikita for WasmSwap UI

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/hack-juno#31]
**Who are you nominating?**
@nikktrfn

**What are you nominating them for?**
For his work on the amazingly beautiful WasmSwap UI!

**Please provide links to their work.**
- https://www.wasmswap.org/
- https://github.com/Wasmswap/wasmswap-interface

**Comment by nikktrfn** [comment]
Thanks so much for the nomination! It was a pleasure to work on the UI, and I'm looking forward to building some new exciting features for WasmSwap UI (spoiler alert; pools are coming up soon!)

**Comment by nullmames** [comment]
man i love this. looking forward to aping into poo coins by the bucket full

**Comment by ben2x4** [comment]
Nikita has crushed it leading the WasmSwap UI. He has spent a tons of hours working with our designers and getting the front end not only working but looking amazing! His code is super clean and will serve as a great example for future dApps.
