### ISSUE TITLE
[Nomination]

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#32]
**Who are you nominating?**
I don't really like this practice of "self-nomination", but I don't want to go and ask other people to nominate me, so I nominate myself one more time)

**What are you nominating them for?**
For the article-guide "Juno Network: How to add Juno-testnet to Keplr and get test-$JUNO", that bring a lot of new users to community, and also was really helpful in testing of Juno Network, and https://juno.omniflix.co/
It shows real usability of Juno Network, and give a practice for users. 
This guide was one of the first guides about Juno, and a lot of people join community after it.

**Please provide links to their work.**

https://antropocosmist.medium.com/juno-testnet-guide-6269baa3fc05

**Comment by JakeHartnell** [comment]
Consolidating info into one nomination, closing in favor of #28. Great work!
