### ISSUE TITLE
[Nomination] validator cyberG

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#33]
**Who are you nominating?**

Validator web34ever - https://t.me/HeKit  <br />
and  <br />
validator cyberG - https://t.me/cryptoq11 <br />

**What are you nominating them for?**

For online workshop "Deploy smart-contract on Juno Network" (part 1 and 2) for russian-speakers validators and developers. <br />
Part 1: At this workshop, web34ever and cyberG was showing how to prepare PC for deploying smart-contracts on Juno Network. <br />
More than 10 people was participating in online. And after this online we have a video, that can be used as educational material for future generation of validators and developers. <br />

Part 2: At this workshop, web34ever and cyberG was showing how to deploy smart-contracts on Juno Network. <br />
More than 10 people was participating in online. Several people was deploying smart-contracts on Juno-test-net-Lucia. And after this online we have a video, that can be used as educational material for future generation of validators and developers. <br />
 
**Please provide links to their work.**
part 1: <br />
https://youtu.be/xjGj8PIkrKU <br />
part 2: <br />
https://youtu.be/SuPByXkjbKk <br />

**Comment by JakeHartnell** [comment]
Making this page about cyberG, in case you or anyone else has anything to add. Will also mention this on web34ever's page #34.

**Comment by JakeHartnell** [comment]
Mentioned on #21
