### ISSUE TITLE
[Nomination] validator web34ever

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#34]
**Who are you nominating?**

Validator web34ever - https://t.me/HeKit  <br />

**What are you nominating them for?**

For the creating "Smart Contract ERC20 Tutorial on Juno testnet" <br />
It really helps to people, who are not developer, to deploy smart-contract on Juno Network, and bring a lot of value to the Network and community! <br />

**Please provide links to their work.**

https://github.com/cybernekit/JunoSmartContract/blob/main/README.md

**Comment by JakeHartnell** [comment]
See also: https://github.com/CosmosContracts/hack-juno/issues/35

**Comment by JakeHartnell** [comment]
Also mentioned on #33:
> **Who are you nominating?**
> 
> Validator web34ever - https://t.me/HeKit and validator cyberG - https://t.me/cryptoq11
> 
> **What are you nominating them for?**
> 
> For online workshop "Deploy smart-contract on Juno Network" (part 1 and 2) for russian-speakers validators and developers. Part 1: At this workshop, web34ever and cyberG was showing how to prepare PC for deploying smart-contracts on Juno Network. More than 10 people was participating in online. And after this online we have a video, that can be used as educational material for future generation of validators and developers.
> 
> Part 2: At this workshop, web34ever and cyberG was showing how to deploy smart-contracts on Juno Network. More than 10 people was participating in online. Several people was deploying smart-contracts on Juno-test-net-Lucia. And after this online we have a video, that can be used as educational material for future generation of validators and developers.
> 
> **Please provide links to their work.** part 1: https://youtu.be/xjGj8PIkrKU part 2: https://youtu.be/SuPByXkjbKk

**Comment by JakeHartnell** [comment]
Mentioned on #21
