### ISSUE TITLE
[Nomination] Again validator web34ever! He is unstoppable!

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#35]
**Who are you nominating?**

Validator web34ever - https://t.me/HeKit  <br />

**What are you nominating them for?**

For the creating of russian translation of "Smart Contract ERC20 Tutorial on Juno testnet"  - Инструкция по созданию Смарт контракта ERC20 в Juno testnet lucina <br />

It really helps to russian-speaking developers and not only to deploy smart-contract on Juno Network, and bring more decentralization to the Network by involving in the process people who don't speak english very good. It's a big value for the community! <br />

**Please provide links to their work.**

https://github.com/cybernekit/JunoSmartContract/blob/main/READMERUS.md

**Comment by JakeHartnell** [comment]
If you have multiple entries for the same person, please put them all in the same ticket. Makes it easier to review. THANKS.

**Comment by Antropocosmist** [comment]
I will try, but the problem, that people do something for Juno at the different time.
Do I need to edit my previous nominations?

**Comment by JakeHartnell** [comment]
> I will try, but the problem, that people do something for Juno at the different time.
> Do I need to edit my previous nominations?

No need to edit the previous one, just keep in mind for the future. : )
You can always edit or add comments to the previous nominations.

**Comment by JakeHartnell** [comment]
Duplicate of #34
