### ISSUE TITLE
[Nomination] Sistla from OmniFlix Network

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#36]
**Who are you nominating?**
Sistla from OmniFlix Network: t.me/Mina_ru_pricesvAbhishek

**What are you nominating them for?**
For amazing User Interface for Juno Network.
This UI is not only UI, but the great example of how Juno Network will be cool and user-friendly!
Because of this UI, people, who are just common users, can test Juno Network! 

**Please provide links to their work.**
https://juno.omniflix.co/

**Comment by JakeHartnell** [comment]
Mentioned on #21
