### ISSUE TITLE
[Nomination] to the POSTHUMAN validator for help in organizing and editing the video workshop "Deploying smart contracts on the Juno network" part 1 + part 2

### ISSUE THREAD

**Issue by cybernekit** [CosmosContracts/hack-juno#37]
Who are you nominating?
POSTHUMAN validator: @antropocosmist

What are you nominating them for?
for help in organizing and editing the video workshop "Deploying smart contracts on the Juno network" part 1 + part 2
It will take a long time to organize an event, record a video, edit a video and upload a video, and then a promo video. Much more than just deploying a smart contract.
And now we have 2 awesome videos to help deploy a smart contract on the Juno network!

Please provide links to their work.

Part 1: https://youtu.be/xjGj8PIkrKU
Part 2: https://youtu.be/SuPByXkjbKk

**Comment by giansalex** [comment]
I see many nominations for the same user, this can be added as a comment in the initial nomination

**Comment by JakeHartnell** [comment]
Moved to #28
