### ISSUE TITLE
[Nomination] Validator POSTHUMAN

### ISSUE THREAD

**Issue by Vgk88** [CosmosContracts/hack-juno#38]
**Who are you nominating?**

Validator POSTHUMAN - https://t.me/Antropocosmist

**What are you nominating them for?**

For helping in  "The Validator Show #6 | Juno Network: Testing the COSMOS" and editing video

**Please provide links to their work.**

https://youtu.be/ggRdwiGduCY

**Comment by JakeHartnell** [comment]
Moving to #28. Thanks for nominating.
