### ISSUE TITLE
[Nomination] natlotzy

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/hack-juno#40]
**Who are you nominating?**
@natlotzy

**What are you nominating them for?**
Building a nice Token Sale Dapp template for the CW20 Sale Contract. Long $POOD.

**Please provide links to their work.**
https://github.com/natlotzy/juno-sale-dapp
https://juno-sale-dapp.vercel.app/

**Comment by ben2x4** [comment]
@natlozy did great work here!

**Comment by natlotzy** [comment]
Thanks @JakeHartnell, it was a pleasure participating. I look forward to contributing and learning more!
