### ISSUE TITLE
[Nomination] Anneyash for WasmSwap Design

### ISSUE THREAD

**Issue by ben2x4** [CosmosContracts/hack-juno#43]
**Who are you nominating?**
@anneyash

**What are you nominating them for?**
Designing the first version WasmSwap UI and providing design assistance throughout the project.

**Please provide links to their work.**
https://www.wasmswap.org/
https://github.com/Wasmswap/wasmswap-interface

![wasmswap1](https://user-images.githubusercontent.com/86395884/135581345-c0a7bd90-3aee-439b-95c0-43489e8d9153.jpg)
![wasmswap2](https://user-images.githubusercontent.com/86395884/135581353-acf5100e-5cb3-43e6-b9be-d99cbbd0c63a.jpg)

**Comment by giansalex** [comment]
Should WasmSwap be nominated as a project (including participants) ?

**Comment by JakeHartnell** [comment]
> Should WasmSwap be nominated as a project (including participants) ?

Good question. I think everyone who has been a part of it has been nominated. Personally, I think it's a bit easier to score if there are individuals behind the nomination... but if a team really wanted to be nominated _as a team_ we could figure that out. Open to feedback and suggestions.
