### ISSUE TITLE
[Nomination] Validator Lavender.five

### ISSUE THREAD

**Issue by dylanschultzie** [CosmosContracts/hack-juno#45]
**Who are you nominating?**
Lavender.five Validators 

**What are you nominating them for?**
Contribution to documentation, as well as helping the community generally in Discord.

**Please provide links to their work.**
https://github.com/CosmosContracts/docs/pull/14

**Comment by Steffcrypto** [comment]
Thank you for your help! Was looking on youtube and google for over 2 hours and you solved it in less then 10 min :)

**Comment by Steffcrypto** [comment]
@JakeHartnell how to connect my Keplr to my exodus wallet and how to claim Juno and Osmo
