### ISSUE TITLE
[Nomination] Sputnik Network Collective

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#47]
**Who are you nominating?**

Sputnik Network collective: https://github.com/SputnikNetwork

**What are you nominating them for?**

For the adding $JUNO to https//sputnik.exchange and to https://SputnikNetworkBot

Now users can send tips with $JUNO directly in Twitter!
Just write in any comment with any other text or without:
<@username> <amount>juno #sputnik

For example:
@SputnikNetwork 0.123juno #sputnik

It will send 0.123 $JUNO from your balance to the balance of twitter-user @SputnikNetwork

! To send tips with $JUNO you need to have it on your balance
‼️ To top-up your balance with $JUNO, visit https://sputnik.exchange/ or https://t.me/SputnikNetworkBot —> "Deposit" —> JUNO

- No fees for depositing, withdrawing or sending tips!
- Tech Support: https://t.me/SputnikNetwork

**Please provide links to their work.**

https//sputnik.exchange
https://SputnikNetworkBot
https://twitter.com/SputnikNetwork/status/1445420421172678657

**Comment by nullmames** [comment]
who specifically are on this team?
