### ISSUE TITLE
[Nomination] BroBro

### ISSUE THREAD

**Issue by blockcreators** [CosmosContracts/hack-juno#52]
**Who are you nominating?**
BroBro

**What are you nominating them for?**
The awesome information stats board + telegram bot

**Please provide links to their work.**
https://monitor.bronbro.io/d/juno-stats/juno-stats?orgId=2
Bot can be seen on telegram

**Comment by bro-n-bro-2** [comment]
Hi there!
Thanks for this nomination, really appreciate it.
Want to add to this list other, less popular, but informative board - https://monitor.bronbro.io/d/juno-graph/

https://github.com/bro-n-bro/prometheus_exporter

We've created Telegram bot:
![image](https://user-images.githubusercontent.com/89855562/136553331-f8fb6b1f-103c-4f66-8665-84e1202c63c3.png)
You can see how it works in main Juno and price channels.

https://github.com/bro-n-bro/tg-price-bot

Moreover, we  helped users with their question in first days.
Actively participated in twitter life: https://twitter.com/Bro_n_Bro/with_replies
