### ISSUE TITLE
[Nomination] Nominate POSTHUMAN (I don't understand how to add this info to previous nomination, because, there is link-on-link-on-link, so sorry me)

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#53]
**Who are you nominating?**

https://github.com/Antropocosmist

**What are you nominating them for?**

For full video guide, how to add $JUNO to Kepler + how to buy $JUNO at Osmosis + how to stake (delegate_ $JUNO with OmniFlix + how to vote for proposals in Juno Network with OmniFlix + for explanation of how all it works

**Please provide links to their work.**

https://youtu.be/Z-M8pBSVks0

**Comment by JakeHartnell** [comment]
Just comment on #28 in the future and add things. : )

**Comment by JakeHartnell** [comment]
Added this to #28.
