### ISSUE TITLE
[Nomination] Cros Nest

### ISSUE THREAD

**Issue by fgatin** [CosmosContracts/hack-juno#54]
**Who are you nominating?**
The Cros Nest team 

**What are you nominating them for?**
- Writing Relayer instructions
- Running a relayer
- Helping the community on Discord and Telegram

**Please provide links to their work.**
- [Relayer instructions ](https://github.com/CosmosContracts/docs/pull/16)
- [Relayer](https://www.mintscan.io/juno/account/juno19pjtx7dah2fquf7udyxjv94h0eraha78nyj9w4) 
- Look for @theBro, @Galadrin, @emuLOAD, and @Florent Discord and Telegram

**Comment by bro-n-bro-2** [comment]
Nice boards! Seems, you were inspired by our work.
