### ISSUE TITLE
[Nomination] Highlander - Cosmverse

### ISSUE THREAD

**Issue by Wolfcontract** [CosmosContracts/hack-juno#64]
**Who are you nominating?**

Highlander @HighlanderCosmos

**What are you nominating them for?**

Many months of work on Cosmverse in collaboration with @giansalex 

**Please provide links to their work.**

https://cosmverse.com

**Comment by nullmames** [comment]
closing in favor of https://github.com/CosmosContracts/hack-juno/issues/14
