### ISSUE TITLE
[Nomination] GianSalex - Cosmverse

### ISSUE THREAD

**Issue by Wolfcontract** [CosmosContracts/hack-juno#65]
**Who are you nominating?**

Giansalex @giansalex

**What are you nominating them for?**

Several months of work on Cosmverse the first NFT marketplace on Juno in collaboration with Highlander

**Please provide links to their work.**

https://cosmverse.com

**Comment by nullmames** [comment]
https://github.com/CosmosContracts/hack-juno/issues/13

Who are you nominating?
@giansalex (Giancarlos Salas)

What are you nominating them for?
Being an OUTSTANDING contributor. Also for running, RPC nodes for lucina. 🙏

Please provide links to their work.

    Updgrading the CosmWasm code explorer CosmJS verision, adding Keplr support, and showing transaction time in the execution info. 

Upgrade cosmjs/stargate  CosmWasm/code-explorer#62

Gitpod Workspace https://github.com/giansalex/cosmwasm-workspace

Keplr CW20 tokens: Fix Add Token (cw20)

Fix Add Token (cw20) chainapsis/keplr-extension#134

cosmwasm dApps upgrade: Stargate v0.25 upgrade

Stargate v0.25 upgrade CosmWasm/dApps#81

dApps works on Juno
https://dapps.juno.giansalex.dev/names/
https://dapps.juno.giansalex.dev/cw20-wallet/
https://dapps.juno.giansalex.dev/staking/
https://github.com/disperze/wrapped-dapp

Add custom mint module juno#36

Split contract: https://github.com/disperze/cw-contracts/tree/master/contracts/split

Lockbox contract: https://github.com/disperze/cw-contracts/tree/master/contracts/lockbox

Wrap contract https://github.com/disperze/cw-contracts/tree/master/contracts/wrap

NFT-Marketplace - Cosmverse - https://github.com/CosmosContracts/Cosmverse

Contracts - cw721, nft-market

**Comment by nullmames** [comment]
closed #13

**Comment by nullmames** [comment]
Append:

    Dark theme
    Upload wasm binary
    Instantiate new contracts

Live: https://blueprints.juno.giansalex.dev/
Repo: https://github.com/giansalex/juno-codes

**Comment by nullmames** [comment]
refer to https://github.com/CosmosContracts/hack-juno/issues/65
