### ISSUE TITLE
[Nomination] Meow - Stargaze.zone

### ISSUE THREAD

**Issue by spacepotahto** [CosmosContracts/hack-juno#70]
**Who are you nominating?**
Our favorite cat with heterochromia, @JakeHartnell
Although he's a judge for Hack Juno and so _would not be eligible for prizes_, some of us want to nominate him anyway to show some appreciation for his work:
https://discord.com/channels/816256689078403103/859298738282168330/898989460203638854 (note the reactions too)
https://discord.com/channels/816256689078403103/859298738282168330/899014390689452082

**What are you nominating them for?**
Starting and contributing to cw-dao: https://github.com/DA0-DA0/cw-dao
And most importanty, for having a hand in many aspects of the project in general; see below.

**Please provide links to their work.**
He's done a lot, but here are some general highlights:

1. cw-dao Contributor
https://github.com/DA0-DA0/cw-dao
2. Active Discord moderator especially on Validators related channels
Search his handle on Discord to see his activities.
3. Organizing all the testnets (and contributed to organizing mainnet) genesis ceremonies
See all Discord pinned messages from him, and search his handle. He makes sure networks get launched, which involves writing documentation, debugging things (e.g. starport in the earlier testnets, bad genesis files, gentx validation scripts, etc.), making sure relevant PRs get merged, herding node operators on Discord, etc.
https://github.com/CosmosContracts/testnets/commits/main
https://github.com/CosmosContracts/mainnet/commits/main
4. Keeping track of and actively nominating people for Hack Juno
https://github.com/CosmosContracts/hack-juno/issues

**Comment by giansalex** [comment]
I think Jake can't be nominated because is Juno Core . :sweat_smile:
Juno core devs have vesting accounts.

**Comment by spacepotahto** [comment]
I know, I prefaced with that. Some people on Discord expressed interest in nominating him, so I thought I might as well start something even though he's not elgible for prizes

**Comment by giansalex** [comment]
I will take advantage of this nomination... :innocent:
Thanks @Wolfcontract, @blockcreators, great job starting JUNO and for all support👏

**Comment by JakeHartnell** [comment]
> I will take advantage of this nomination... innocent Thanks @Wolfcontract, @blockcreators, great job starting JUNO and for all supportclap

We have a truely amazing community!

**Comment by Highlander-maker** [comment]
Well done core team. Hats off on an amazing, professional, slick and patient release of one of the hottest projects in the space right now. Brought me in to this as a rookie and ive learned loads on the way with you guys time and patience. :)...
