### ISSUE TITLE
[Nomination] I would like to nominate Alex Lynham (the-frey)

### ISSUE THREAD

**Issue by blockcreators** [CosmosContracts/hack-juno#9]
He has done amazing work with documentation, video tutorials, airdrop code, community help and the faucet! (and more)

**Comment by JakeHartnell** [comment]
Well deserved @the-frey. :tada:

**Comment by Highlander-maker** [comment]
agree. I have learned a lot from @the-frey s video and well documented instructions. :)

**Comment by the-frey** [comment]
😊 glad folk have found it useful!

**Comment by dimiandre** [comment]
Great job! 👍

**Comment by JakeHartnell** [comment]
One more thing! @the-frey has done great work helping with CosmWasm documentation in prep for v1.0. Here's the PR: https://github.com/InterWasm/docs/pull/3

Thanks for helping to get it shipped. :pray:

**Comment by JakeHartnell** [comment]
ANOTHER GREAT VIDEO: https://www.youtube.com/watch?v=7Snfn7o99Yw

**Comment by JakeHartnell** [comment]
The whole video series for those who are interested: https://www.youtube.com/playlist?list=PLBRsqZrQcloqex_4Td5TBE74ZZ9WtO0F2

**Comment by the-frey** [comment]
Not sure if it has been mentioned, cos it was/is ancient history, but adding it for completeness - built the stakedrop tool 
https://github.com/CosmosContracts/juno-stakedrop-viewer-backend
https://github.com/CosmosContracts/juno-stakedrop-viewer

Also contributed a port of EIP-2981 for NFT royalties back upstream into CW

**Comment by JakeHartnell** [comment]
Wanted to add that @the-frey has been incredibly helpful answering questions in Discord. Truly a great knowledge resource for the community.

**Comment by JakeHartnell** [comment]
In #25, @Highlander-maker mentioned:
> for clear documentation not only for Cosmovisor but all the other content he has contributed his time to.

https://docs.junochain.com/validators/setting-up-cosmovisor
