### ISSUE TITLE
[Nomination] SpaceMerch

### ISSUE THREAD

**Issue by dimiandre** [CosmosContracts/hack-juno#95]
**Who are you nominating?**
SpaceMerch

**What are you nominating them for?**
They are building ecommerce integration with NFTs and Cosmos Native + cw20 tokens, and a DAO with various actors managing designs shipments and sales

**Please provide links to their work.**
https://twitter.com/spacemerchdao?s=21&t=UzDwpi_Sfuy9quDkVTMXaA

this nomination is for the development part, not related with the merch they gave for free in the past conferences

**Comment by JakeHartnell** [comment]
Proper place to apply and new process is mentioned here: https://medium.com/hack-juno-dao/hack-juno-280670cd71b2
