### ISSUE TITLE
[Idea] Nodejumper.io & Juno collaboration

### ISSUE THREAD

**Issue by asadovka** [CosmosContracts/hack-juno#96]
**Who you are**

We are the [Nodejumper.io](https://nodejumper.io/) team - a professional PoS validator that is focused on both consumers & validators, helping them to easily join the Cosmos SDK blockchain community and make it bigger and more valuable

**What is your idea?**

Our project will provide deep on-chain data analytics - Juno decentralization map with advanced tokenomics stats. For the validator community we’ll create Juno node manual & automatic installation/ synchronization scripts (with custom RPC support), node monitoring/alerting tools and cheat sheet for composing/running the most popular Juno CLI commands

**Comment by JakeHartnell** [comment]
We only fund things that have been built.
